name: skin_diseases
description: تطبيق تشخيص الأمراض الجلدية باستخدام الذكاء الاصطناعي - Professional Skin Disease Diagnosis App
publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI والتصميم
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0

  # اختيار الصور
  image_picker: ^1.0.4
  camera: ^0.10.5+5

  # الأذونات
  permission_handler: ^11.0.1

  # معالجة الصور
  image: ^4.1.3

  # إدارة الحالة
  provider: ^6.1.1
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

  # التخزين المحلي وقاعدة البيانات
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  path: ^1.8.3

  # الشبكة والـ HTTP
  http: ^1.1.0
  dio: ^5.3.2

  # التاريخ والوقت
  intl: ^0.18.1

  # الرسوم المتحركة
  lottie: ^2.7.0
  animations: ^2.0.8
  flutter_staggered_animations: ^1.1.1

  # التحكم في الشاشة
  flutter_native_splash: ^2.3.5

  # الملاحة
  go_router: ^12.1.1

  # الأيقونات
  flutter_launcher_icons: ^0.13.1

  # التنبيهات والإشعارات
  fluttertoast: ^8.2.4
  awesome_dialog: ^3.1.0

  # الرسوم البيانية
  fl_chart: ^0.64.0

  # PDF والتقارير
  pdf: ^3.10.7
  printing: ^5.11.1

  # مشاركة الملفات
  share_plus: ^7.2.1

  # للذكاء الاصطناعي (اختياري - يتطلب إعداد إضافي)
  # pytorch_mobile:
  # tflite_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  # الأصول
  assets:
    - assets/images/
    - assets/models/
    - assets/animations/
    - assets/icons/
    - assets/sounds/

  # الخطوط
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300

# إعدادات الشاشة الافتتاحية
flutter_native_splash:
  color: "#F8FFFE"
  image: assets/images/splash_logo.png
  android_12:
    image: assets/images/splash_logo.png
    color: "#F8FFFE"

# إعدادات الأيقونات
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21